### ISSUE TITLE
Denied permission

### ISSUE THREAD

**Issue by wessoll** [surrealroad/Safari-Push-Notifications#10]
I fulfill all the requirements like using SSL (valid certificate), uploading files to the root folder etc. But the only message I get is "You have denied this website permission to send push notifications". If I log the request_uri to the error_log, the path remains "/". I also uploaded the .htaccess file to my /var/www/html (root). The function variable remains empty thus. If i replace this with a string "pushPackages", like the function name, it goes into that block successfully for downloading the push package. But in my browser instead of showing me the permission dialog, it downloads the file to my Download folder. I can see the animation from the Safari download button to my Download folder. Should this happen?

**Comment by surrealroad** [comment]
Can you provide me with the URL to your push service

**Comment by wessoll** [comment]
gladly, can I mail it to you, the url is kind a private;)

**Comment by surrealroad** [comment]
sales@surrealroad dot com

**Comment by surrealroad** [comment]
Your SSL certificate is not valid (host name mismatch). I get a warning in both chrome and safari, so you need to address that first.

**Comment by wessoll** [comment]
my bad, it is just changed last evening, you can remove the "upc." part in front of the url... but it should just jump right into the pushPackages block right.

**Comment by surrealroad** [comment]
if i do that, all that happens is that a zip file downloads

**Comment by surrealroad** [comment]
not unless you've made changes to the code?

I see the url `/v1/push` does not work, is your htaccess file installed correctly? Are you using Apache?

**Comment by wessoll** [comment]
Oh wait a sec, now things are falling into pieces. In my apache config file, AllowOverride was set to none. Changed it and it works! Thank you for the help and awesome code!
