### ISSUE TITLE
Not possible to add new tokens in the database if the user is not connected 

### ISSUE THREAD

**Issue by Djibs** [surrealroad/Safari-Push-Notifications#11]
I just noticed that for months, there are no new mac added to the database. I just understand why.

If you are a user logged on to the site and you sign up to receive pushs -> your mac is saved in the database

If you do not have an account on the site (ie "userID": "0") ->
no new mac added to the database

**Comment by surrealroad** [comment]
that shouldn't be the case, I see the plenty of new users being added on my test system with a userid of 0

**Comment by mart03** [comment]
Im confirm this, just for my server i don't use "mysqli" so i have edit all for "mysql" and is work

**Comment by Djibs** [comment]
it does not work on my site or http://iphoneaddict.fr

or on the secure page https://iphoneaddict.fr

**Comment by surrealroad** [comment]
It looks like the prompt to subscribe is working there. The only thing I can think of is that your Mysql table has been set up to not allow duplicates on the userid column? Otherwise I don't see anything in the code that would prevent it from working.

**Comment by Djibs** [comment]
No, my table allows duplicates to UserID
look

![djibs 2014-04-03 a 23 54 34](https://cloud.githubusercontent.com/assets/1236842/2609741/cfa08878-bb7a-11e3-926a-d7c99fc65a61.jpg)
![djibs 2014-04-03 a 23 54 56](https://cloud.githubusercontent.com/assets/1236842/2609742/cfa39f9a-bb7a-11e3-93d8-9b1e61df2fe2.png)

**Comment by Djibs** [comment]
I have the problem on my two sites

(mysql 5.6)

**Comment by Djibs** [comment]
I have a temporary solution: if I change userID for all, with 100 instead of 0 for visitors who do not have an account, it works!

**Comment by surrealroad** [comment]
Ok that gives me an idea: on line 56, change `$userid = "";` to `$userid = 0;` and see if it works

**Comment by surrealroad** [comment]
ok, got it-- you have your mysql table set to userid NOTNULL, which is why you were getting new rows rejected.

Should work for you now in the latest version

**Comment by Djibs** [comment]
So if I change 0 to NULL in the structure of my table, it will work?

**Comment by Djibs** [comment]
it's works when i change $userid = ""; to $userid = 0;

Thank youy

**Comment by surrealroad** [comment]
:)
