### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Er-Kalpesh** [surrealroad/Safari-Push-Notifications#12]
Hello,

I need help here
1)how to create pushpackage? what will be the URL to create push package?
i am using https://www.domain.com/safari/index.php/pushPackages
and changed code and set $function = $path[2];
but here whats the $version = $path[0] ?
$body = json_decode($body, true); is empty
$userid = $body["id"]; is empty too
2)how to use log?

Requests must be mapped to /v1/request (for example https://push.yoursite.com/v1/pushPackages must be a valid URL) - the included .htaccess file should do this for you if you upload the files to the server root

My using now https://www.domain.com/safari/index.php/v1/pushPackages
$version = $path[2];
$function = $path[3];
so now have query here:
$body = json_decode($body, true); is empty
$userid = $body["id"]; is empty too

so what to do here?
please help me

in website.json getting token like:
    "authenticationToken": "authenticationToken_",

**Comment by surrealroad** [comment]
> My using now https://www.domain.com/safari/index.php/v1/pushPackages

You must be providing a URL in the form `https://www.domain.com/v1/pushPackages`, if you put the files, including the .htaccess in your root folder `https://www.domain.com/` then it should work correctly.

**Comment by Er-Kalpesh** [comment]
here whats the meaning of $body = @file_get_contents("php://input"); ?

**Comment by surrealroad** [comment]
That captures the JSON request from Safari

**Comment by Er-Kalpesh** [comment]
Sorry Jack James am not getting application, please can you help me out?

You mention that "You must be providing a URL in the form https://www.domain.com/v1/pushPackages" so which form?

I am direct entering https://www.domain.com/v1/pushPackages url in safari,

now debugging code like:

<pre>
if ($function == "pushPackages") { //Build and output push package to Safari
    $body = @file_get_contents("php://input");
    $body = json_decode($body, true);
        echo "< pre >---";
        print_r($body);
        exit; 
</pre>

so here am getting blank array.

so what’s wrong I am doing here?

**Comment by surrealroad** [comment]
please provide me with a link to your site, and undo any changes to `index.php`

**Comment by Er-Kalpesh** [comment]
Here is the link https://www.domain.com/safari/index.php/

**Comment by surrealroad** [comment]
As I said before, that URL will not work. Your push service must be the root, https://www.imobdevtech.com not https://www.imobdevtech.com/safari/
