### ISSUE TITLE
Send Notifications by Packages

### ISSUE THREAD

**Issue by Djibs** [surrealroad/Safari-Push-Notifications#13]
Hello,

Firstly thank you for your work.

Is it possible to send notifications by packages? because currently only the first 2000 registered devices receive push (approximately). the others receive nothing.

Why not send per 1000 tokens:

-> Sending 1000
-> We close the connection with Apple
-> Another 1000
-> We close
-> ...

I currently have 17,000 registered Mac, 15000 not receive anything. the problem is present in all users of your code.

Regards

**Comment by Djibs** [comment]
I have no error in the logs. It is stated that all devices have received the push, but a lot of people do receive nothing
![djibs 2014-06-12 a 16 01 29](https://cloud.githubusercontent.com/assets/1236842/3258518/74eadcb6-f23a-11e3-86eb-6dc3726ab66c.jpg)

**Comment by surrealroad** [comment]
It should already work that way https://github.com/surrealroad/Safari-Push-Notifications/blob/master/index.php#L125

Basically if the push request fails for a specific device, it will disconnect and try again (up to 3 times). If you are being told by the response that devices were notified successfully, then this is because APNS is not reporting back any problem.

In the first instance I would suggest getting in touch with Apple to find out why notifications are being ignored. If this is a known limitation, then I will of course modify the code to take this into account.

**Comment by Djibs** [comment]
I saw it on the Apple forum if it helps :

"I'm trying to implement Safari Push Notification on a big scale website (tens of thousands of Mac readers) and I think that I'm opening and closing the sockets correctly. To test this I came up with the silly idea of sending myself 100, 500, 1000 and 2000 push notifications. The problem is that I always receive only a random number of them. 100 is ok. After that, sometimes I get 120, sometimes 129, sometimes 130 and so forth for oll the cases above 100.
Is a limitation from OS X Mavericks or my server doesn't deliver all of them? The APNS feedback service doesn't complain."

We can try with packages of 100 tokens?

**Comment by surrealroad** [comment]
Hmm I see that post, I also see that none of these posts are getting any official response, I guess only five people are using push notifications… :(

Anyway, if you want, try this branch: https://github.com/surrealroad/Safari-Push-Notifications/tree/batch-notify which will force a reconnection every 100 devices. If you do, let me know how you get on (my test site is around 1500 devices, so I can't verify it myself)

**Comment by Djibs** [comment]
I just put the new index.php file

Can you subscribe to this test? http://iphoneaddict.fr

Tell me when you are registered and I am sending a push test

**Comment by surrealroad** [comment]
I'm running Yosemite beta, so notifications don't work for me. Try unsubscribing and re-subscribing one of your devices, this should put it to the end of the queue.

**Comment by Djibs** [comment]
No, when I delete my mac, it is not deleted from the database.

I'll remove it manually and put it in the end.

**Comment by surrealroad** [comment]
That's strange. The code to remove from the db has not been touched at all. Makes me wonder if APNS is having problems.

**Comment by Djibs** [comment]
It never worked on my site. My mac is never removed

**Comment by Djibs** [comment]
It seems to work with 100

**Comment by mart03** [comment]
It's works for me too !

**Comment by surrealroad** [comment]
Excellent, I will fold into the master branch. Thanks both for the feedback

**Comment by Djibs** [comment]
:-)
