### ISSUE TITLE
PHP Warning:  openssl_x509_read

### ISSUE THREAD

**Issue by DohaSoul** [surrealroad/Safari-Push-Notifications#20]
Hi!

The push notification has been working for about a year, then the certificate expired.
I made another certificate but whenever I tried to subscribe it says "You have denied this website permission to send push notifications"
and the error log is:
PHP Warning:  openssl_x509_read() [<a href='function.openssl-x509-read'>function.openssl-x509-read</a>]: supplied parameter cannot be coerced into an X509 certificate! in createPushPackage.php on line 80
PHP Warning:  openssl_pkcs7_sign() [<a href='function.openssl-pkcs7-sign'>function.openssl-pkcs7-sign</a>]: error getting cert in createPushPackage.php on line 82
PHP Warning:  file_get_contents(/tmp/pushPackage1426701463/signature) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in createPushPackage.php on line 85
PHP Warning:  file_get_contents(/tmp/pushPackage1426701463.zip) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or directory in index.php on line "echo file_get_contents($package_path);"
PHP Warning:  unlink(/tmp/pushPackage1426701463.zip) [<a href='function.unlink'>function.unlink</a>]: No such file or directory in index.php on line "unlink($package_path);"

**Comment by surrealroad** [comment]
i think the important bit is `supplied parameter cannot be coerced into an X509 certificate!` you might want to double-check `CERTIFICATE_PATH` and `CERTIFICATE_PASSWORD` settings

**Comment by DohaSoul** [comment]
I changed the CERTIFICATE_PASSWORD and the first error gone, but I'm still cannot subscribe.
This is the error log:
[19-Mar-2015 09:04:33] PHP Warning:  file_get_contents(/tmp/pushPackage1426745073.zip) [<a href='function.file-get-contents'>function.file-get-contents</a>]: failed to open stream: No such file or index.php on line  "echo file_get_contents($package_path);"
[19-Mar-2015 09:04:33] PHP Warning:  unlink(/tmp/pushPackage1426745073.zip) [<a href='function.unlink'>function.unlink</a>]: No such file or directory in index.php on line "unlink($package_path);"

**Comment by surrealroad** [comment]
Seems like it is not able to create the zip file. Do you have the zip extension installed?

**Comment by DohaSoul** [comment]
I checked the phpinfo, the zip extension is installed and enabled, also the pushPackage1233456789XXX folder is created in the tmp folder every time I tried to subscribe

**Comment by DohaSoul** [comment]
I figure out that when the CERTIFICATE_PASSWORD is having a WRONG password, the error goes.. but if the password is right, the first error comes out which is:

PHP Warning: openssl_x509_read() [function.openssl-x509-read]: supplied parameter cannot be coerced into an X509 certificate! in createPushPackage.php on line 80
PHP Warning: openssl_pkcs7_sign() [function.openssl-pkcs7-sign]: error getting cert in createPushPackage.php on line 82

**Comment by DohaSoul** [comment]
I solved the problem.
All I have to do is to double click on the website_aps_production.cer to open it in the Keychain, THEN I have to export the .p12 key.
I was exporting the .p12 without opening the website_aps_production.cer

Thanks for your time.
