### ISSUE TITLE
Not Getting Request Dialog

### ISSUE THREAD

**Issue by azchipka** [surrealroad/Safari-Push-Notifications#3]
I have set everything up via the directions provided and I am getting the following issues:
1. On one machine it says "You have denied this website permission to send push notifications." If i click the I changed my mind option is just refreshes to show the same thing.
2. On a second machine it just constantly says "requesting permission" but the dialog box never shows up. 

site in question is: https://tchpush.thechipkahouse.com

It is worth noting I have tested the cert and key files on apples production server and they will make and hold a connection through telnet.

Apple Error Console is showing an error on live 8 of the bootstrap.min.js file

Error is TypeError: 'undefined' is not a function (evaluating 'a')

I also enabled the error display on the index page as you suggested to andrebazaglia and I am getting the following error there: Undefined offset: 1 in /home/azchipka/public_html/tchpush/index.php on line 33

which is reference to : $function = $path[1];

Kinda playing the trial and error game at this point. Thinking this problem is related to the certificate since that is such an annoying process in this whole thing.

I ran the command openssl s_client -connect gateway.push.apple.com:2195 -CAfile apns-cert.pem which generated the following error: verify error:num=20:unable to get local issuer certificate
verify return:0

The big problem I am encountering here is that your directions say to use: openssl x509 -in website_aps_production.cer -inform der -out apns-cert.pem -nodes -clcerts to which I am being told by terminal -nodes is an unknown option.

Using the directions referenced from your site for certificate creation found here (http://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1) the certs make and pass the test presented and hold the connection to the server.

Also when I use the testing code provided by apple openssl s_client -connect gateway.push.apple.com:2195 -cert tch.pem -debug -showcerts -CAfile tchpushercert.pem the connection reports fine with no errors.

Thanks in advance for any help you can provide.

**Comment by surrealroad** [comment]
I've just replied to your similar thread at wordpress forums, but for the record:

> You have an invalid SSL certificate for https://tchpush.thechipkahouse.com/
> You'll probably need to resolve that first.
> As for the pem file, that is only required for actually sending a notification. If you are not getting the prompt to subscribe, then it's likely due to your push service setup being wrong somewhere.
> See "common issues" at https://github.com/surrealroad/Safari-Push-Notifications

**Comment by azchipka** [comment]
Changed the SSL cert to a valid signed one. So that is issue is taken care off. 

One question on the common issues it says Requests must be mapped to /v1/request (for example https://push.yoursite.com/v1/pushPackages must be a valid URL) - the included .htaccess file should do this for you if you upload the files to the server root. The folder is there.

Wondering if you could clarify this one for me.

**Comment by surrealroad** [comment]
Ok here's your error:

`Fatal error: Class 'ZipArchive' not found in /home/azchipka/public_html/tchpush/createPushPackage.php on line 99`

might be a PHP extension you need to install

**Comment by azchipka** [comment]
Ok so spot on the Zip extension was not installed. So that is installed now and that error is gone, but it still hasn't resolved the issue.

**Comment by surrealroad** [comment]
what version of safari are you testing with? Can you try updating the server to the latest version if it's anything other than 7.0.0

**Comment by azchipka** [comment]
It's all set now, I am running Safari 7.1 (beta) which was the issue. Coding is set specifically to Safari 7.0; changed this and all is now fine. Thanks

**Comment by surrealroad** [comment]
cool. make sure you update the wordpress plugin (if you're using it) too if you haven't already
