### ISSUE TITLE
You have denied this website permission to send push notifications.

### ISSUE THREAD

**Issue by DohaSoul** [surrealroad/Safari-Push-Notifications#4]
Its always says: "You have denied this website permission to send push notifications."
and there is nothing inside logs folder, I believe the problem is in the config.php file

1- I upload all the files into https://domain.com/push
so on the WEBSERVICE_URL and ALLOWED_DOMAINS and URL_FORMAT
it should be 'https://domain.com/push' or just 'https://domain.com' ?

2- on CERTIFICATE_PATH
it should be './push/cert.p12' or './push/cert.p12' or just './cert.p12' ?

**Comment by surrealroad** [comment]
From the readme

> Requests must be mapped to /v1/request (for example https://push.yoursite.com/v1/pushPackages must be a valid URL) - the included .htaccess file should do this for you if you upload the files to the server root

So you cannot install this into a subfolder on your server
