### ISSUE TITLE
I'm trying to change the index.php to something else

### ISSUE THREAD

**Issue by DohaSoul** [surrealroad/Safari-Push-Notifications#6]
I changed the index.php to push.php
and changed the .htaccess from:

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php/$1 [L]

to:

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ push.php/$1 [L]

it worked perfect..

but now the 404 error page is not working, it redirect the visitors to push.php instead of 404 error page.

Is there any way to fix that with .htaccess?

**Comment by surrealroad** [comment]
no idea I'm afraid. Also be sure that https://yoursite/v1/pushPackage still works after changing the htaccess file.
