### ISSUE TITLE
Delete push* and push*.zip in the /tmp folder from the server after sending the push.

### ISSUE THREAD

**Issue by Djibs** [surrealroad/Safari-Push-Notifications#7]
Delete push\* and push*.zip in the /tmp folder from the server after sending the push.

Files accumulate over time and after a while there is more space.

**Comment by surrealroad** [comment]
You're referring to the pushpackages? Unfortunately there's no way of knowing how long it will take for someone's browser to download each one. It would probably be possible to periodically scan through and clean up but it doesn't seem worth the effort.  I will try to put something in that at least cleans up the files used to build the zip.

**Comment by Djibs** [comment]
Yes pushpackages\* and pushpackages*.zip

Currently, I'm running a cron job every 5 minutes :

_/5 \* \* \* \* /bin/rm -r /tmp/push_

(before the first "/" star and the last does not appear above)

**Comment by surrealroad** [comment]
https://github.com/surrealroad/Safari-Push-Notifications/commit/3366c873c083417ea0083b7cb236809745f0486b will clear up the directories, I still need to do the code to clean up the zips after a certain time

**Comment by surrealroad** [comment]
https://github.com/surrealroad/Safari-Push-Notifications/commit/f33c3702df186393359910e66192c6f64889964f should do the trick
