### ISSUE TITLE
No check after send push

### ISSUE THREAD

**Issue by mart03** [surrealroad/Safari-Push-Notifications#8]
Hello, 
I have problem, i have some message error to significate not all push are send. 

And i see the server have not check after send push and if the connection fail/bug between two push all rest of push are ignored.. 

If you have solution, 
Thanks,
Martin

**Comment by surrealroad** [comment]
The latest version has some logging included, so maybe that will provide more details

**Comment by mart03** [comment]
I just update the plugin, but i don't find any error_log or other files in folder plugin..
I have this error on my logs serveur :
[03-Apr-2014 03:15:17 America/New_York] PHP Warning:  fwrite(): SSL: Broken pipe in /home/ipodtou3/https/index.php on line 181

**Comment by surrealroad** [comment]
Hi the plugin only logs responses from the server, and can be found in the admin panel at the bottom of the plugin settings page after notifications are sent.

Broken pipe indicates a problem with your network connection, or that APNS is terminating the connection earlier. See here for more details: http://stackoverflow.com/questions/2626054/get-ssl-broken-pipe-error-when-try-to-make-push-notification.

**Comment by mart03** [comment]
Hi, ok for plugin. 

I have already see this post, and is not respond really in my issues, i have test a connection APNS and he works perfectly, and some of my customers recept push, the serveur just stop when he see an invalid token, and he stop delevery.

**Comment by surrealroad** [comment]
ok, do you know what the invalid token is?

**Comment by mart03** [comment]
No i don't know. That is a problem

**Comment by surrealroad** [comment]
Next time you do a push via the wordpress plugin (0.9) it should tell you how many notifications were sent (in the settings page), OR you can do a manual notification from there and it will tell you. Probably you can use this information to find which device id is failing. Do you have a lot of registered devices? Did you look into the database push table to see if anything was obviously wrong?

**Comment by mart03** [comment]
I make push manual, this morning with the new version (0.9) i don't see it how many notification are send. (The counter doen't work for me i don't know why, i have update server for that but nothing..) 
I have 3015 users for the moment, and i have see nothing of abviously wrong in my table.

**Comment by surrealroad** [comment]
My mistake, it looks like manual push doesn't return the server response, I will address that in a patch. You'll have to check next time you post something.

**Comment by mart03** [comment]
Okay, so what i need to do ? Im waiting a patch ?

**Comment by surrealroad** [comment]
Next time you send an automatic push -- when you publish a wordpress post, check the log at the bottom of the settings page.

**Comment by mart03** [comment]
Here we go : http://i.imgur.com/JdRjjGO.png 
Same error...

**Comment by surrealroad** [comment]
does it say right at the bottom how many succeeded?

**Comment by mart03** [comment]
No, is blank, and just so much errors !

**Comment by surrealroad** [comment]
I think at this point all I can do is refer you to the Apple dev forums, I can't see any issue with your setup or code.

**Comment by mart03** [comment]
Maybe Cloudflare do an error, is weird..
Ok thanks im investigate..

**Comment by mart03** [comment]
I just test one things, if my token is in first, i recept my push but if i delete my token and im a last, don't recept.. So i think push are send by "packet" and the last packet are no send, i have contact other friend use your system, and is same for him !

**Comment by surrealroad** [comment]
Please try the version on this branch https://github.com/surrealroad/Safari-Push-Notifications/tree/broken-pipe

This should reset the APNS connection after 1000 devices, maybe it will help.

**Comment by Djibs** [comment]
it does not work for me if I put my token at the end of the table

**Comment by mart03** [comment]
I just try and he say : 3034 of 3034 device(s) notified 
But im not notified..

**Comment by surrealroad** [comment]
but are you still getting a broken pipe error?

**Comment by mart03** [comment]
No i don't, but why im not recept also ? ..

**Comment by surrealroad** [comment]
Good, so we have fixed that issue at least, I'll fold the changes into the main branch.

As for why you are now not receiving push notifications, that's something different, the notification requests are all being received by APNS, which means there might be a problem on Apple's side.

From the release notes of Safari 7.0.3: 

> - Fixes an issue that could block receipt of push notifications from websites 

You can try updating to 10.9.3 beta (which includes Safari 7.0.3) and see if it works. I have 7.0.3 installed myself so I just registered for push notifications for your site, and will let you know if anything comes through

**Comment by mart03** [comment]
All rights, i have 7.0.3 too, i just send push now, tell me if you recept anything. 

Thanks

**Comment by surrealroad** [comment]
no I didn't receive anything. You can try reducing the variable $connectLimit (line 116) maybe to 500 and see if that makes any difference

**Comment by mart03** [comment]
Ok i have broken pipe error now. 
and : 2667 of 3029 device(s) notified

**Comment by surrealroad** [comment]
try changing it to 2

**Comment by mart03** [comment]
The request is too long 1.2min and cancel the push

**Comment by surrealroad** [comment]
maybe try 10 or 20?

**Comment by mart03** [comment]
Ok with 20 is work no error, but i have nothing recept...

**Comment by surrealroad** [comment]
Really no idea then. You're pushing to ~3000 devices, 20 at a time, with no reported errors. 
I'm out of ideas.
It must be something at Apple's side, meaning you'll have to file a bug with them, or post a message on the developer forums.

**Comment by surrealroad** [comment]
Actually, I did just think of something-- how long is the title/message you're trying to push? There's a limit.

**Comment by mart03** [comment]
That very weird...

**Comment by surrealroad** [comment]
can you try the latest version, this will return an error if you are trying to push a notification that is too big for the server

**Comment by mart03** [comment]
I have implanted your code, and im trying

**Comment by mart03** [comment]
Is same.. and doens't have error

**Comment by surrealroad** [comment]
well I'm out of ideas. Must be an issue on Apple's side.

**Comment by mart03** [comment]
I have asked to my reader on twitter if they recep or not push safari, and a lot don't recept, but one part of then recept correctly that is very weird...

**Comment by Smoolak** [comment]
Wait a minute I don't call this a patch : https://github.com/surrealroad/Safari-Push-Notifications/commit/a82ce9c156a6489b96d93f0a9589b42bf0d6577b

This is ridiculous, you're only hiding the error... You need to check if the connection is still open every time you send a push and if the connection is not right you just need to call connect_apns again.

You should replace the line 125 for :

if($write === false)
    $apns = connect_apns(APNS_HOST, APNS_PORT, PRODUCTION_CERTIFICATE_PATH);
else
    $success++;

From PHP manual : "fwrite() returns the number of bytes written, or FALSE on error."

You need this error checking because the Apple server close the connection if a bad token is used to send a push, therefor you can even check which token are bad and notify the user of the script in the logs.

**Comment by Smoolak** [comment]
And by the way trying to solve a part of the problem with a "$connectLimit" is not a good idea, you just need to check the connection after every fwrite and reconnect if the connection is closed.

You can also detect a connection error, try to resend the push 3 times and if its keep failing you should just skip the token....

**Comment by surrealroad** [comment]
Yes, it's to suppress the errors, so the log doesn't get flooded (as mentioned on a separate thread). But thanks for the other suggestions, I'll update the code accordingly.

**Comment by surrealroad** [comment]
https://github.com/surrealroad/Safari-Push-Notifications/commit/8e1459ef6809e07333c32b66656c1febcedc475e addresses this last point.
