### ISSUE TITLE
Is SSL obligatory?

### ISSUE THREAD

**Issue by joeharby** [surrealroad/Safari-Push-Notifications#9]
I'm pushing notifications to iOS apps without SSL. Are Safari notifications somehow different or is it uniquely this script that requires an SSL cert?

**Comment by surrealroad** [comment]
The web service "must start with https".  See [this document](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1). SSL is also required to communicate with APNS.

**Comment by joeharby** [comment]
Thanks!
